[tool.black]
line-length = 120
target-version = ['py38']
include = 'epidatpy'

[tool.pylint]
max-line-length = 120
min-public-methods = 1
disable = [
    "R0801",
    "E1101",
    "E0611",
    "C0114",
    "C0116",
    "C0103",
    "R0913",
    "R0914",
    "W0702",
    "too-many-public-methods",
    "too-many-instance-attributes",
]
