name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install Dependencies
        run: |
          make install
      - name: Check Formatting
        run: |
          make lint_ruff
      - name: Check Linting
        run: |
          make lint_pylint
      - name: Check Types
        run: |
          make lint_mypy
      - name: Test
        run: |
          make test
