name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          make install
      - name: Check Formatting
        run: |
          make lint_ruff
      - name: Check Linting
        run: |
          make lint_pylint
      - name: Check Types
        run: |
          make lint_mypy
      - name: Test
        run: |
          make test
