name: Create Release
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "Semantic Version Number (i.e., 5.5.0 or patch, minor, major, prepatch, preminor, premajor, prerelease)"
        required: true
        default: patch

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: main
          ssh-key: ${{ secrets.CMU_DELPHI_DEPLOY_MACHINE_SSH }}
      - name: Reset main branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
      - name: Change version number
        id: version
        run: |
          INPUT="${{ github.event.inputs.versionName }}"
          if [[ $INPUT =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            # apply explicit version
            uv version --frozen "$INPUT"
          elif [[ $INPUT =~ ^(major|minor|patch)$ ]]; then
            # bump current version
            uv version --frozen --bump "$INPUT"
          else
            echo "Invalid version name: $INPUT"
            exit 1
          fi
          NEXT_TAG=$(uv version --short)
          echo "next_tag=$NEXT_TAG" >> $GITHUB_OUTPUT
      - name: Create pull request into main
        uses: peter-evans/create-pull-request@v6
        with:
          branch: release/${{ steps.version.outputs.next_tag }}
          commit-message: "chore: release ${{ steps.version.outputs.next_tag }}"
          base: main
          title: Release ${{ steps.version.outputs.next_tag }}
          labels: chore
          # reviewers:
          assignees: dshemetov
          body: |
            Releasing ${{ steps.version.outputs.next_tag }}.
