name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python3.8 -m venv .venv
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/pip install -e ".[dev]"
      - uses: siacodelabs/setup-pandoc@v1
      - name: Sphinx build
        run: |
          .venv/bin/sphinx-build -b html docs docs/_build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true